# Railway Deployment Configuration for HTTP API
# railway.toml

[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.minimal"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1